title: seyhan project
description: açık kaynak kodlu, kurulumu ve kullanımı kolay ücretsiz ön muhasebe programı
logo : /assets/img/logo.png
app_version: 1.0.23

show_downloads: true

theme: jekyll-theme-minimal

google_analytics: UA-57560424-1